### ISSUE TITLE
How would you feel about a change in the default icon?

### ISSUE THREAD

**Issue by brennanpincardiff** [satRdays/badgeR#14]
I think it would be better if we could change the default icon to the SatRday icon or something R based at least. 
How do you feel about that @dokato?

**Comment by dokato** [comment]
The resean why I'm using "ifmlogoc" is that this is some built-in image in latex (probably from creators of the `ticket` package), so there was no need to deal with image paths etc. which might be confusing for new users. Having said that, I just added a new example here: #12 that shows how to insert a custom logo (awaiting review from @DaveParr).
